name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  pre-commit:
    name: Pre-commit validation
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Setup Terraform Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
      - name: "Install pre-commit tools: terraform-docs, tflint & tfsec"
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          GO111MODULE="on" go get -u github.com/terraform-docs/terraform-docs
          sudo mv $(go env GOPATH)/bin/terraform-docs /usr/local/bin/terraform-docs
          curl -sSLf "$(curl -sS https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip
          unzip tflint.zip && rm tflint.zip
          sudo mv tflint /usr/local/bin/
          go get -u github.com/tfsec/tfsec/cmd/tfsec
          sudo mv $(go env GOPATH)/bin/tfsec /usr/local/bin/tfsec
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
      - name: Run terraform init on examples folders
        run: |
          for DIR in $(find ./examples -type d); do
            pushd $DIR
            terraform init
            popd
          done
      - name: Run pre-commit hooks
        uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Terratest tests
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
          terraform_wrapper: false
      - name: Setup Go Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Terraform Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
      - name: Run tests
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          cd test && go test -v -timeout 20m
